# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build & Verify Project

on:
  push:
    branches: [ "main" ]
    paths:
      - 'poetry.*'
      - 'conda*.lock'
      - 'environment.yml'
      - 'pyproject.toml'
      - 'setup.cfg'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'poetry.*'
      - 'conda-*.lock'
      - 'environment.yml'
      - 'pyproject.toml'
      - 'setup.cfg'

jobs:
  build-linux:
    name: Build with ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-conda-lock-${{ hashFiles('conda-linux-64.lock') }}
        restore-keys: |
          ${{ runner.os }}-conda-lock-${{ hashFiles('conda-linux-64.lock') }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: false
        environment-file: ./conda-linux-64.lock
        activate-environment: ./.venv

    - name: Check core dependencies
      run: |
        conda info
        conda activate ./.venv
        conda info
        poetry --version

    - name: Install dependencies
      run: |
        poetry install

    - name: Check code quality
      run: |
        poetry run black --check .
        poetry run isort . --check --diff
        poetry run flake8 . --count --show-source --statistics

    - name: Test Run
      run: |
        poetry run python -m src.app
