# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build & Verify Project

on:
  push:
    branches: [ "main" ]
    paths:
      - 'poetry.*'
      - 'conda*.lock'
      - 'environment.yml'
      - 'pyproject.toml'
      - 'setup.cfg'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'poetry.*'
      - 'conda-*.lock'
      - 'environment.yml'
      - 'pyproject.toml'
      - 'setup.cfg'

jobs:
  build-linux:
    name: Build with ubuntu-latest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    env:
      CONDA_ENV_NAME: pytorch2-env

    steps:
    - uses: actions/checkout@v3

    - name: Cache conda packages
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-lock-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda-linux-64.lock') }}

    - name: Cache conda environment
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache
        CACHE_NUMBER: 0
      with:
        path: ${{ env.CONDA }}/envs/${{ env.CONDA_ENV_NAME }}
        key: ${{ runner.os }}-conda-env-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda-linux-64.lock') }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        use-only-tar-bz2: true # for caching to work properly
        auto-activate-base: false
        environment-file: ./conda-linux-64.lock
        activate-environment: ${{ env.CONDA_ENV_NAME }}

    - name: Check core dependencies
      run: |
        conda info
        poetry --version

    - name: Install dependencies
      run: |
        poetry install

    - name: Check code quality
      run: |
        poetry run black --check .
        poetry run isort . --check --diff
        poetry run flake8 . --count --show-source --statistics

    - name: Test Run
      run: |
        poetry run python -m src.app
